service: aws-api-tecnical-test

useDotenv: true

custom:
  esbuild:
    bundle: true
    minify: false 
  tableName: peopleswapi-table-${sls:stage}
  swapi_base_url: https://swapi.py4e.com/api/

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    NODE_ENV: ${sls:stage}
    SWAPI_BASE_URL: ${self:custom.swapi_base_url}
    PEOPLE_TABLE: ${self:custom.tableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [PeopleSwapiTable, Arn]
  httpApi:
    cors: true

functions:
  hello:
    handler: index.handler
    events:
      - httpApi: 
          path: /{any+}
          method: ANY

resources:
  Resources:
    PeopleSwapiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-esbuild
  - serverless-dotenv-plugin
